# -*- coding: utf-8 -*-
"""Copy of Final-task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LOtTBVWnz6bZ-J5urNELscN9tB_0yQXx

# **Data Understanding**
"""

from google.colab import drive  #connect to google drive
drive.mount('/content/drive')

import pandas as pd
df =pd.read_csv('/content/drive/MyDrive/Course/Rakamin/Final task/loan_data_2007_2014.csv')  #load dataset
df.head()

df.shape #number of rows and columns

df.info()

df.describe() #descriptive statistics

df['loan_status'].value_counts() #target distribution

#target distribution

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))

sns.countplot(
    x='loan_status',
    data=df,
    palette='viridis'
)

plt.title('Distribusi Loan Status', fontsize=16)
plt.xlabel('Loan Status', fontsize=12)
plt.ylabel('Jumlah Data', fontsize=12)

plt.xticks(rotation=45, ha='right')
plt.tight_layout()

plt.show()

df.isnull().sum().sort_values(ascending=False).head(10) #missing values

df.duplicated().sum() #check for duplication

df['loan_amnt'].hist(bins=50)
plt.title('Distribusi Loan Amount')
plt.show()

df['annual_inc'].hist(bins=50)
plt.title('Distribusi Annual Income')
plt.show()

sns.boxplot(x=df['annual_inc'])
plt.title('Boxplot Annual Income')
plt.show()

plt.figure(figsize=(6,4))
sns.scatterplot(x='annual_inc', y='loan_amnt', data=df)
plt.title('Loan Amount vs Annual Income')
plt.show()

df.describe().T

"""# **Exploratory Data Analysis (EDA)**

**UNIVARIATE ANALYSIS**
"""

#Numerical distribution

plt.figure(figsize=(6,4))
sns.histplot(df['loan_amnt'], bins=50, kde=True)
plt.title('Distribusi Loan Amount')
plt.show()

#Numerical distribution

sns.histplot(df['annual_inc'], bins=50, kde=True)
plt.title('Distribusi Annual Income')
plt.show()

#Categorical distribution

sns.countplot(x='home_ownership', data=df, palette='Set2')
plt.title('Distribusi Home Ownership')
plt.show()

"""**BIVARIATE ANALYSIS**"""

#create target column from loan_status

good = [
    'Fully Paid',
    'Does not meet the credit policy. Status:Fully Paid'
]

bad = [
    'Charged Off',
    'Default',
    'Late (31-120 days)',
    'Late (16-30 days)',
    'Does not meet the credit policy. Status:Charged Off'
]

# Ambil hanya GOOD & BAD
df = df[df['loan_status'].isin(good + bad)]

# Buat target
df['target'] = df['loan_status'].apply(lambda x: 1 if x in good else 0)

#Income vs Risk

sns.boxplot(x='target', y='annual_inc', data=df)
plt.title('Income vs Credit Risk')
plt.show()

#DTI vs Risk

sns.boxplot(x='target', y='dti', data=df)
plt.title('DTI vs Credit Risk')
plt.show()

#Loan Amount vs Risk

sns.boxplot(x='target', y='loan_amnt', data=df)
plt.title('Loan Amount vs Risk')
plt.show()

"""**CORRELATION ANALYSIS**"""

df_numeric = df.select_dtypes(include=['int64', 'float64'])

plt.figure(figsize=(12,8))
corr = df_numeric.corr()

sns.heatmap(corr, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

corr = df.select_dtypes(include=['int64', 'float64']).corr()

corr_target = corr['target'].sort_values(ascending=False)

print(corr_target.head(10))

corr = df_numeric.corr()

# ambil korelasi terhadap target saja
corr_target = corr['target'].sort_values(ascending=False)

print(corr_target)

#Target Distribution

sns.countplot(x='target', data=df, palette='coolwarm')
plt.title('Distribusi Target (Good vs Bad)')
plt.show()

"""# **Data Preparation**"""

#HANDLE MISSING VALUES

missing_ratio = df.isnull().mean()

cols_to_drop = missing_ratio[missing_ratio > 0.5].index  #If the missing value ratio is more than 50% then it will be deleted

df = df.drop(columns=cols_to_drop)

drop_text = ['desc', 'url', 'title', 'emp_title']

df = df.drop(columns=drop_text, errors='ignore')

df = df.fillna(df.median(numeric_only=True)) #fill missing value with median

df = df.fillna('Unknown')

#create target column from loan_status

good = [
    'Fully Paid',
    'Does not meet the credit policy. Status:Fully Paid'
]

bad = [
    'Charged Off',
    'Default',
    'Late (31-120 days)',
    'Late (16-30 days)',
    'Does not meet the credit policy. Status:Charged Off'
]

# Take only GOOD & BAD
df = df[df['loan_status'].isin(good + bad)]

# Create a target
df['target'] = df['loan_status'].apply(lambda x: 1 if x in good else 0)

#removal of features that contain data leakage, namely features that contain information after the loan is running

drop_cols = [
    'loan_status',
    'total_pymnt',
    'total_pymnt_inv',
    'total_rec_prncp',
    'total_rec_int',
    'recoveries',
    'last_pymnt_amnt'
]

df = df.drop(columns=drop_cols, errors='ignore')

cat_cols = df.select_dtypes(include=['object']).columns

#encoding

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in cat_cols:
    df[col] = le.fit_transform(df[col].astype(str))

#data split

from sklearn.model_selection import train_test_split

X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

#normalization on numeric features

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#addressing data imbalance using SMOTE

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

"""# **Data Modelling**

**LOGISTIC REGRESSION**
"""

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train_smote, y_train_smote)

y_pred_lr = lr.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

print("Logistic Regression")
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

roc_auc_score(y_test, lr.predict_proba(X_test)[:,1])

#cross Validation

from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(lr, X_train_smote, y_train_smote, cv=5)

print("CV Score:", cv_scores.mean())

#Checking for overfitting or underfitting

train_acc = lr.score(X_train_smote, y_train_smote)
test_acc = lr.score(X_test, y_test)

print("Train:", train_acc)
print("Test:", test_acc)

"""**RANDOM FOREST**"""

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)

rf.fit(X_train_smote, y_train_smote)

y_pred_rf = rf.predict(X_test)

print("Random Forest")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

y_prob_rf = rf.predict_proba(X_test)[:, 1]

roc_auc_rf = roc_auc_score(y_test, y_prob_rf)

print("ROC-AUC Random Forest:", roc_auc_rf)

#cross validation

from sklearn.model_selection import cross_val_score

cv_scores_rf = cross_val_score(rf, X_train_smote, y_train_smote, cv=5)

print("CV Score:", cv_scores_rf.mean())

#Checking for overfitting or underfitting

train_acc_rf = rf.score(X_train_smote, y_train_smote)
test_acc_rf = rf.score(X_test, y_test)

print("Train:", train_acc_rf)
print("Test:", test_acc_rf)

# Logistic Regression
y_prob_lr = lr.predict_proba(X_test)[:, 1]

# Random Forest
y_prob_rf = rf.predict_proba(X_test)[:, 1]

from sklearn.metrics import roc_auc_score

roc_auc_lr = roc_auc_score(y_test, y_prob_lr)
roc_auc_rf = roc_auc_score(y_test, y_prob_rf)

print("ROC-AUC Logistic Regression:", roc_auc_lr)
print("ROC-AUC Random Forest:", roc_auc_rf)

from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt

# hitung curve
fpr_lr, tpr_lr, _ = roc_curve(y_test, y_prob_lr)
fpr_rf, tpr_rf, _ = roc_curve(y_test, y_prob_rf)

plt.figure(figsize=(7,5))

# plot Logistic Regression
plt.plot(fpr_lr, tpr_lr, label=f'LogReg (AUC = {roc_auc_lr:.2f})')

# plot Random Forest
plt.plot(fpr_rf, tpr_rf, label=f'Random Forest (AUC = {roc_auc_rf:.2f})')

# garis random
plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison')
plt.legend()

plt.show()

"""# **Evaluation**"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred_rf)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - Random Forest')

plt.show()

#taking false negative data

import pandas as pd

wrong_pred = pd.DataFrame(X_test, columns=X.columns).copy()
wrong_pred['actual'] = y_test.values
wrong_pred['pred'] = y_pred_rf

# False Negative (BAD tapi diprediksi GOOD)
fn = wrong_pred[(wrong_pred['actual'] == 0) & (wrong_pred['pred'] == 1)]

fn.head()

fn.describe().T

import pandas as pd

pd.DataFrame(X_test, columns=X.columns).describe().T